apiVersion: "argoproj.io/v1alpha1"
kind: AppProject
metadata:
  name: big-data
  namespace: argocd
spec:
  description: "Contain all Big Data deployments"
  sourceRepos:
    - https://trinodb.github.io/charts/
    - https://github.com/henrypham67/big-data-on-eks.git
    - https://strimzi.io/charts/
    - https://airflow.apache.org
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true