FROM --platform=linux/amd64 apache/airflow:2.10.4

# [Start-providers]
# [End-providers]

# [Start-python-libs]
# install dbt into a virtual environment
RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
    pip install --no-cache-dir dbt-trino && deactivate

# Install all other libs
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
# [End-python-libs]