apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: trino-dbt-user
  namespace: external-secrets
spec:
  externalSecretName: trino-dbt-user
  namespaceSelectors:
  - matchLabels:
      kubernetes.io/metadata.name: trino
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: trino-dbt-user
      creationPolicy: Owner
      deletionPolicy: Delete
    dataFrom:
      - extract:
          # AWS Secrets Manager secret's name
          key: trino_dbt_user