apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: kafka-connect-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: big-data
  source:
    repoURL: "https://github.com/henrypham67/big-data-on-eks.git"
    targetRevision: HEAD
    path: "apps/kafka/kafka_connect/cluster"
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      # - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
  